version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 12
  ignore:
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.3
    - 5.1.0
    - 5.1.1
  - dependency-name: window-resize-subject
    versions:
    - 1.4.4
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: node-notifier
    versions:
    - 8.0.1
